### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by needsomevibe** [mudachyo/PixelTap#1]
WebSocket connection to 'wss://api-clicker.pixelverse.xyz/socket.io/?EIO=4&transport=websocket' failed: WebSocket opening handshake was canceled

**Comment by mudachyo** [comment]
Switch on the VPN

**Comment by needsomevibe** [comment]
Hi, vpn and proxy didn't help

**Comment by needsomevibe** [comment]
![image](https://github.com/mudachyo/PixelTap/assets/170326925/9881fd31-4113-4cf4-9ff0-2fe24beadf9d)

**Comment by mudachyo** [comment]
There are no other options
