### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by tankow79** [mudachyo/PixelTap#2]
Does not work:
1. Launching a new game
2. Clicking on the super strike and defense card

I managed to fix:
1. Launching a new game
By replacing
`const restartBtn = document.querySelector('#root > div > div > div:nth-child(1) > div > div > div._footerCard_bgfdy_87 > div._buttons_bgfdy_124 > button._button_uyw8r_1._purple_uyw8r_31._textUppercase_uyw8r_28');`
on
`const restartBtn = document.querySelector("#root > div > div > div:nth-child(1) > div > div > div._footerCard_bgfdy_87 > div._buttons_bgfdy_124 > button._button_fe4eh_1._purple_fe4eh_31._textUppercase_fe4eh_28");`

I need help with 2.

**Comment by mudachyo** [comment]
Corrected.
