### ISSUE TITLE
UPDATE SCRIPT

### ISSUE THREAD

**Issue by paaavann** [mudachyo/PixelTap#5]
PixelTap has updated their ui and old script no longer works.
![image](https://github.com/mudachyo/PixelTap/assets/170100881/62600bf5-da33-4099-b5c5-5a7ac7d17804)

Also in this new update players now leave if they are losing.
![image](https://github.com/mudachyo/PixelTap/assets/170100881/757dcb4e-c3f4-46dc-80f5-bd9190952c39)

Update the script

**Comment by mudachyo** [comment]
updated.
