### ISSUE TITLE
Please update script

### ISSUE THREAD

**Issue by jaylinlucero** [mudachyo/PixelTap#8]
![image](https://github.com/mudachyo/PixelTap/assets/67506511/d1198ba2-a66a-4beb-8aa1-b7bd150bfe73)
I wonder if this is an accident or if they tweaked something in the bot... I see that they often hit 1 at a time

**Comment by bitserj** [comment]
unrelated, but could you add a script for W-coin @wcoin_tapbot ?

**Comment by mudachyo** [comment]
The script has been updated and is working correctly. The character does "-1" damage if you don't hit. Most likely, the script stops hitting when it pauses between each click. In such moments, it shows that you are doing "-1" damage.
